// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsCoqXH8YvoHTWwaVgsHw3Errc3-39zQ0',
    appId: '1:1040124724616:web:5ae85798332e541f84e63d',
    messagingSenderId: '1040124724616',
    projectId: 'expense-tracker-a0830',
    authDomain: 'expense-tracker-a0830.firebaseapp.com',
    storageBucket: 'expense-tracker-a0830.firebasestorage.app',
    measurementId: 'G-1G8CS0R1PM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp7sIl9U35JM4Tz7jhVGwaB-S9ov3e1sM',
    appId: '1:1040124724616:android:8676514eabe38a3184e63d',
    messagingSenderId: '1040124724616',
    projectId: 'expense-tracker-a0830',
    storageBucket: 'expense-tracker-a0830.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXbpdxlmK-YmWoyWy79Acdl4FoDCG0Bdc',
    appId: '1:1040124724616:ios:56571ffe1c40098384e63d',
    messagingSenderId: '1040124724616',
    projectId: 'expense-tracker-a0830',
    storageBucket: 'expense-tracker-a0830.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXbpdxlmK-YmWoyWy79Acdl4FoDCG0Bdc',
    appId: '1:1040124724616:ios:56571ffe1c40098384e63d',
    messagingSenderId: '1040124724616',
    projectId: 'expense-tracker-a0830',
    storageBucket: 'expense-tracker-a0830.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsCoqXH8YvoHTWwaVgsHw3Errc3-39zQ0',
    appId: '1:1040124724616:web:91022e5c87b90e2e84e63d',
    messagingSenderId: '1040124724616',
    projectId: 'expense-tracker-a0830',
    authDomain: 'expense-tracker-a0830.firebaseapp.com',
    storageBucket: 'expense-tracker-a0830.firebasestorage.app',
    measurementId: 'G-HZWJWSESSD',
  );

}